language: node_js
node_js:
  - 14

services:
  - docker

script:
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverse-proxy ./udagram-reverse-proxy

- docker tag udagram-api-feed johnsonml/udagram-api-feed:latest
- docker tag udagram-api-user johnsonml/udagram-api-user:latest
- docker tag udagram-frontend johnsonml/udagram-frontend:latest
- docker tag udagram-reverse-proxy johnsonml/udagram-reverse-proxy:latest

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push johnsonml/udagram-api-feed:latest
- docker push johnsonml/udagram-api-user:latest
- docker push johnsonml/udagram-frontend:latest
- docker push johnsonml/udagram-reverse-proxy:latest